### PR TITLE
Add linear blocks optimization

### PR DESCRIPTION
**Pull request by larsk21**
See `LinearBlockVisitor::visit` for an explanation when blocks can be joined.

### CODE REVIEW

**Comment by larsk21** [comment]
Most of the mjtests run fine, but there is one with a weird bug. Compiling and running `compile/CellularAutomaton.mj` will result in an inverted output grid (where the program should output the character `'` a `#` is output and vice versa), otherwise it runs fine.

Even more weird:
- when compiled with the firm backend, the bug is not present
- when compiled with the advanced register allocator (even without other optimizations), the bug is present
- when compiled with the dumb allocator (without other optimizations), a segmentation fault occurs, originating in an `movq (_, _, 8), _` instruction in the method `CellularAutomaton::run`

Looking at the graphs, the optimization doesn't change much, only a few empty blocks are skipped. This seems to be valid, since it compiles with the firm backend, but I have no idea where the error might come from.

**Comment by N-Maas** [comment]
Interesting, I will try to look into it soon.

**Comment by g4rgoil** [comment]
The optimized graph for `run` contains a block with two control flow predecessors pointing to nodes in the same block (just different results of a condition). I don't have any evidence to suggest it is related to this bug in any way, but it could cause problems (for example when trying to insert blocks for critical edge resolution).

image

**Comment by larsk21** [comment]
Very interesting! But having a block with multiple equal predecessors is still valid in a Firm graph, isn't it?

**Comment by g4rgoil** [comment]
> Very interesting! But having a block with multiple equal predecessors is still valid in a Firm graph, isn't it?

Yes, as far as I know that is absolutely valid in Firm. In some cases you can optimize it to an unconditional jump, but in general (for example in this case) you can't because of `Phi`s.

**Comment by larsk21** [comment]
> Yes, as far as I know that is absolutely valid in Firm. In some cases you can optimize it to an unconditional jump, but in general (for example in this case) you can't because of `Phi`s.

Yes, that's also done in this optimization.

So we will fix this in the PhiResolver? Do you know who implemented it?

**Comment by g4rgoil** [comment]
> So we will fix this in the PhiResolver? Do you know who implemented it?

Yeah, this needs to be fixed in `PhiResolver`, it may also require changes to `PermutationSolver`. I believe it was implemented by @N-Maas originally.

**Review by N-Maas — APPROVED** [review]
Looks good to me and works well.

**Pull request merged**
