### PR TITLE
Clean up some tests

### PR DESCRIPTION
**Pull request by larsk21**
- rename test classes to fit Maven's naming conventions
- resolve IDE warnings (unused variables)

### CODE REVIEW

**Comment by 0xNB** [comment]
Approved, if you want you can add more cleaning up of warnings from our IDEs in this merge request. Or if you want me to I'll collect some

**Comment by 0xNB** [comment]
For example we could also think about cleaning up Optionals as return type or inner fields, or remove unused methods

**Comment by 0xNB** [comment]
For example we could also think about cleaning up Optionals as return type or inner fields, or remove unused methods

**Comment by larsk21** [comment]
> For example we could also think about cleaning up Optionals as return type or inner fields, or remove unused methods

That would be valid in some places (for example in `DataType`), where context makes it clear whether or not to expect a value. When the caller would have to check for `null` to be safe, we should keep using `Optional` and `isPresent`/`isEmpty` instead.

**Pull request merged**
