### PR TITLE
Remodel standard library

### PR DESCRIPTION
**Pull request by larsk21**
Standard library calls are now a special construct without `System` or `System.out`/`System.in` being defined on its own. The following code yields "`System` cannot be resolved":
```
// inside some method
if (System.out == null) {
  ...
```

detailed changes:
- remove global variable `System`
- change `StandardLibrary` to include only names and method definitions
- explicitly check method invocations to identify standard library calls
- allow removing the object of a method invocation
- add tests for standard library calls

### CODE REVIEW

**Comment by 0xNB** [comment]
Hmm what about the comparison of `System.in` == `System.in`. Since both return the same stream the check should also work

**Comment by larsk21** [comment]
> Hmm what about the comparison of `System.in` == `System.in`. Since both return the same stream the check should also work

There is no concept of stream in MiniJava. We were told that system calls are special constructs and that comparisons like `System == System` are not valid. I would guess the same holds for `System.in` and `System.out`.

**Comment by larsk21** [comment]
> The implementation in the visitor looks good, it seems to solve the issues of the previous implementation. The only potential problem I see is how we can map the `MethodNode`s of the standard library to the corresponding Firm entities (see [StandardLibraryEntities](https://github.com/larsk21/compiler-minijava/blob/1552174ab99f18ad3bf9de96e09a13e5150759d9/src/main/java/edu/kit/compiler/transform/StandardLibraryEntities.java)).

When reaching a `MethodInvocationExpressionNode`, we would have to check whether it is a standard library call or not. If it is, we can use the `method : StandardLibraryMethod` attribute of `StandardLibraryMethodNode` to determine the correct method.

If you don't want to make this test with `invocation.getDefinition() instanceof StandardLibraryMethodNode` (or a small visitor), we can add a flag to `MethodNode` or something like that.

**Comment by g4rgoil** [comment]
> When reaching a `MethodInvocationExpressionNode`, we would have to check whether it is a standard library call or not. If it is, we can use the `method : StandardLibraryMethod` attribute of `StandardLibraryMethodNode` to determine the correct method.
> 
> If you don't want to make this test with `invocation.getDefinition() instanceof StandardLibraryMethodNode` (or a small visitor), we can add a flag to `MethodNode` or something like that.

OK, I didn't notice that Enum existed, as it isn't part of this PR. I think the test you described should do the job. Additionally, we can add a method to `StandardLibraryEntities` which returns the corresponding `Entity` for each entry of the Enum.

**Review by g4rgoil — APPROVED** [review]

**Pull request merged**
